UKHomeOffice/return-of-documents

bin/deploy.sh
kube/certs/certificate-external.yml
kube/certs/certificate-internal.yml

There is an error accessing the branch URL.
The branch domain name used should contain notprod naming. The certificates and script were missing the naming convention.
Adding the branch naming convention to the deploy.sh and certificates.

ROD-72: renaming branch domain and certificates

---

apps/cancel-request/fields/index.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/pages.json
apps/cancel-request/translations/src/en/validation.json
assets/js/index.js

[ROD-35](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-35) - 'Main applicant details' page - Cancel Request
Allow us to create ROD
- Added full name with validations
- Added date of birth with validations
- Added nationality with validations

CNC - 2 Create 'Main applicant details' page

---

apps/cancel-request/fields/index.js
apps/cancel-request/index.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/validation.json

[ROD-54](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-41) - Create "Who are you legally representing?" page for - Cancel Request
Allow the user to select who they are legally representing.
- Added title and radio buttons for the page
- Created validations for said page.

ROD-41 CNC - "Who are you legally representing?" page

---

apps/cancel-request/fields/index.js
apps/cancel-request/index.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/validation.json

[ROD-44](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-44) - Create Are you a dependant or a guardian of a dependant page for ROD - Cancel Request
Allows user to select if they are a dependant or a guardian of a dependant
- Added Heading and radio buttons for page
- Added validations for page

ROD-44 CNC Are you a dependant or a guardian of a dependant page

---

apps/cancel-request/index.js
apps/cancel-request/translations/src/en/journey.json
apps/cancel-request/translations/src/en/pages.json
apps/cancel-request/views/cancel-request-start.html
apps/cancel-request/views/cancellation-received.html
apps/cancel-request/views/layout.html
apps/cancel-request/views/partials/confirmation-alert.html
apps/report-documents-not-received/index.js
apps/report-documents-not-received/translations/src/en/journey.json
apps/report-documents-not-received/translations/src/en/pages.json
apps/report-documents-not-received/views/documents-not-received-start.html
apps/report-documents-not-received/views/layout.html
apps/report-documents-not-received/views/partials/confirmation-alert.html
apps/report-documents-not-received/views/partials/documents-not-received.html
apps/report-documents-not-received/views/report-submitted.html
apps/rod/fields/index.js
apps/rod/index.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/journey.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json
apps/rod/views/partials/confirmation-alert.html
apps/rod/views/partials/related-services-menu.html
apps/rod/views/request-received.html
apps/rod/views/start.html
assets/scss/app.scss

- [ROD-74](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-74) - ROD - 2 Create WHO IS COMPLETING screen
- Added new pages for WHO IS COMPLETING page inROD main flow
- Added required field validation for all pages
- Added necessary step configuration and field specific variables.
- Added fix for the backlink on the first page after the start pages in all three flow - [ROD-95](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-95)
- Added serviceName in journey.json for all three flows and added the layout.html to render <title>
- Added template for confirmation screen for all three flows and added required css

ROD-74 - ROD main form - Added who is completing page

---

apps/report-documents-not-received/fields/index.js
apps/report-documents-not-received/index.js
apps/report-documents-not-received/translations/src/en/fields.json
apps/report-documents-not-received/translations/src/en/validation.json
assets/scss/app.scss

Relates [ROD-37](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-37)
Add application type page for DNR

ROD-37-add application type page

---

apps/report-documents-not-received/fields/index.js
apps/report-documents-not-received/index.js
apps/report-documents-not-received/translations/src/en/fields.json
apps/report-documents-not-received/translations/src/en/validation.json

[ROD-38](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-38)
Add visa type page to DNR journey

ROD-38-add dnr visa type page

---

README.md
apps/cancel-request/behaviours/custom-validation.js
apps/cancel-request/fields/index.js
apps/cancel-request/index.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/validation.json
package.json

[ROD-62](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-62) - Which reference number can you provide page
- Added new page for Which reference number can you provide?
- Added inbuilt(hof) and default validations as per the requirement
- Tested locally

ROD-62 Reference number can you provide page

---

apps/cancel-request/translations/src/en/validation.json

[ROD-100](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-100) - Record number error message
Error message for max and min length has been updated
**Before**
**After**

ROD-100 Record number error message

---

apps/cancel-request/fields/index.js
apps/cancel-request/index.js
apps/cancel-request/sections/summary-data-sections.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/pages.json
apps/cancel-request/translations/src/en/validation.json

[ROD-63](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-63) - Contact details page
Added new page for Contact details
Local and branch testing

ROD-63 Contact Details page 

---

apps/rod/index.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/views/content/proof-identity.md
apps/rod/views/proof-of-identity.html

What?
[ROD-89](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-89) - ROD - 8 Create a PROOF of IDENTITY screen
Why?
Be informed how user can use their passport once returned 
How?
Added text to proof of identity page
Testing?
Screenshots (optional)
Anything Else? (optional)
Check list
I have reviewed my own pull request for linting issues (e.g. adding new lines)
I have written tests (if relevant)
I have created a JIRA number for my branch
I have created a JIRA number for my commit
I have followed the chris beams method for my commit https://cbea.ms/git-commit/
Ensure drone builds are green especially tests
I will squash the commits before merging

ROD 89 Proof of Identity

---

apps/rod/translations/src/en/pages.json
apps/rod/views/cannot-travel.html
apps/rod/views/content/cannot-travel.md
assets/scss/app.scss

[ROD-90](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-90) - ROD - 9 Create a CANNOT TRAVEL page
Be told of any travel restrictions on my passport and display to users 
Added text to cannot travel page 

ROD-90 Cannot travel page

---

apps/report-documents-not-received/fields/index.js
apps/report-documents-not-received/index.js
apps/report-documents-not-received/sections/summary-data-sections.js
apps/report-documents-not-received/translations/src/en/fields.json
apps/report-documents-not-received/translations/src/en/pages.json
apps/report-documents-not-received/translations/src/en/validation.json

Relates [ROD-56](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-56)

ROD-56-add-contact-details-page

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json

- [ROD-80](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-80) - Create an APPLICATION CATEGORY page 
- Creating new pages for APPLICATION CATEGORY page in ROD main flow
- Added necessary step configuration and field specific variables.
- Added required field validation for all pages
- Added summary page entry in summary-data-sections.js and routing logic from Point A(/application) to point B (/reference-number) 
- Added all forks condition to get the get the required pages in the main flow

ROD-80 - Added Create an APPLICATION CATEGORY page 

---

apps/cancel-request/fields/index.js
apps/cancel-request/index.js
apps/cancel-request/sections/summary-data-sections.js
apps/cancel-request/translations/src/en/fields.json
apps/cancel-request/translations/src/en/pages.json
apps/cancel-request/translations/src/en/validation.json

[ROD-45](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-45) - What is the application for page
Local and branch testing

ROD-45 What Is Application For page

---

apps/report-documents-not-received/translations/src/en/pages.json
apps/report-documents-not-received/views/report-submitted.html
assets/scss/app.scss

relates [ROD-60](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-60)

ROD-60-add report submitted page

---

apps/rod/translations/src/en/pages.json
apps/rod/views/cancelling-application.html
apps/rod/views/content/cancelling-your-application.md

[ROD-44](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-91) Create a cancel your application page -  for ROD - Main Flow
Provides user with information about cancelling their request.
- Added information via an MD and HTML file.

ROD-91 Create a cancel your application page

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json

- [ROD-94](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-94) - Create a main applicant's DETAILS page
- Creating new pages for main applicant's DETAILS page in ROD main flow
- Added necessary step configuration and field specific variables.
- Added required field validation for all pages

ROD-94 - Added main applicant details page

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json
assets/scss/app.scss

- [ROD-93](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-93) - Create a YOUR DOCUMENTS page
- Creating new pages for YOUR DOCUMENTS page page in ROD main flow
- Added necessary step configuration and field specific variables.
- Added required field validation for all pages
- Added summary page fields to verify user inputs

ROD-93 - Added your documents page in ROD main flow

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json

[ROD-121](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-121) - Create NOTES page

ROD-121 extra notes page

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json

[ROD-109](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-109) - Contact Details page (main flow)
Local and branch testing

ROD-109 Contact Details page

---

apps/rod/behaviours/who-is-completing.js
apps/rod/fields/index.js
apps/rod/index.js
apps/rod/translations/src/en/buttons.json
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json
apps/rod/views/content/is-legal-rep-declaration.md
apps/rod/views/content/is-main-app-declaration.md
apps/rod/views/content/is-sponsor-declaration.md
apps/rod/views/declaration.html
assets/js/index.js
assets/scss/app.scss

Relates [ROD-123](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-123), [ROD-124](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-124), [ROD-125](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-125)
Add dynamic declaration page depending on who is applying

ROD-123-add declaration pages for legal rep, app, sponsor

---

apps/rod/fields/index.js
apps/rod/index.js
apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/fields.json
apps/rod/translations/src/en/pages.json
apps/rod/translations/src/en/validation.json

[ROD-104](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-104) - Create an ENTER main APPLICANT'S ADDRESS main flow
Allows user to enter main applicant address
- Added inputs
- Added validations for page

RODD-104 Main Applicants Address

---

apps/cancel-request/fields/index.js
apps/report-documents-not-received/behaviours/custom-validation.js
apps/report-documents-not-received/fields/index.js
apps/report-documents-not-received/index.js
apps/rod/fields/index.js
test/_unit/sections/summary-data-sections.spec.js
test/_unit/utils/utils.spec.js
utils/index.js

- International telephone number validator 
- Unit tests
- International telephone number validator has been added to the utils so it can be reused across journeys
- Have added unit tests for utils as these are used across journeys

ROD-127 Refactor telephone number validator

---

apps/rod/sections/summary-data-sections.js
apps/rod/translations/src/en/pages.json

[ROD-122](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-122) - Create a CHECK YOUR ANSWERS page for ROD main flow.
Allows users to check the information they have provided and possible change it.
- Added correct fields
- Followed the figma design

ROD-122 Create check your answers page

---

apps/cancel-request/views/content/cancel-request-start.md
apps/report-documents-not-received/views/content/documents-not-received.md
apps/rod/views/content/rod-start.md

[ROD-163](https://collaboration.homeoffice.gov.uk/jira/browse/ROD-163) - Add UAN in the 'what you need' section at each start page flow.
Allows the user to know the requirements before proceeding with the form.
Added text to each flows MD file.

ROD-163 Add UAN in the 'what you need' section at each start page

---

config.js

Update feedback url by turning it into an environment variable
To ensure consistency with the other services
Remove hard coded feedback url and replace with environment variable

ROD-164: Update feedback URL
